name: Visualize

on:
  push:
    branches: 
    - main

jobs:
  visualize:
    name: visualize
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4
    - name: Repo Visualizer
      uses: githubocto/repo-visualizer@0.9.1
      with:
        output_file: diagram.svg
        should_push: false
        artifact_name: artifact
